# pythonのコードをlintします
name: check format and lint
on: [pull_request]
jobs:
  pysen:
    name: lint python code
    runs-on: ubuntu-latest  # linux ubuntu環境で
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # PRのbranchへcheckout
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v2 #pythonをダウンロードする
        with:
          python-version: 3.9.2 #pythonのダウンロードバージョン
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -  # poetryのインストール
      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH # poetryのpathを通す
      - name: Install Dependencies
        run: poetry install --no-interaction  # poetryでパッケージインストール
      - name: Run linter
        run: make lint  # lint起動